version: "2.4"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PASSWORD: 'temp123'
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - file-db:/var/lib/mysql
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
  api:
    build: .
    ports:
      - 8000:8000
volumes:
  file-db:
