version: "2.4"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PASSWORD: 'temp123'
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - file-db:/var/lib/mysql
      - ./cooperativa.sql/:/docker-entrypoint-initdb.d/cooperativa.sql
    container_name: cooperunidos_db
    networks:
      - cooperunidos-network

  api:
    # image: ncscorpelini/projeto-integrador_api:0.1.3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    container_name: cooperunidos_api
    env_file:
      - ./.env
    extra_hosts:
      - host.docker.local:host-gateway
    networks:
      - cooperunidos-network
    depends_on:
      - db


volumes:
  file-db:

networks:
  cooperunidos-network:
    driver: bridge
