name: Construcao de CI

on: 
  push:
    branches:
      - "main"
  
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.base_ref}}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC+8
          format: 'YYYYMMDDHHmm'
           
      - name: Creating a docker tag
        run: |
          echo "DOCKERTAG=$(echo '${{ steps.time.outputs.time }}')" >> $GITHUB_ENV
      
      - name: Build Docker
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
          echo 'Building docker image'
          docker build --no-cache --rm -t hub.docker.com/${{secrets.DOCKER_USERNAME}}/projeto-integrador-api:$DOCKERTAG .
          echo 'Pushing the docker image ...'
          echo 'Done (-:'

      - name: Trivy Scanning
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'hub.docker.com/${{secrets.DOCKER_USERNAME}}/projeto-integrador-api:${{env.DOCKERTAG}}'
          format: 'table'
          output: 'trivy-results.txt'

      - name: Upload report Trivy
        uses: actions/upload-artifact@v2
        with:
          name: Trivy
          path: |
            trivy-results.txt

      
      - name: Push to docker 
        run: docker push hub.docker.com/${{secrets.DOCKER_USERNAME}}/projeto-integrador-api:$DOCKERTAG

      - name: End
        run: |
          echo "Thats all folks!"
