name: Construcao de CI

on: 
  push:
    branches:
      - "main"
  
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.base_ref}}

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC+8
          format: 'YYYY-MM-DD-HH-mm-ss'
           
      - name: Creating a docker tag
        run: |
          DOCKERTAG = "${{ steps.time.outputs.time }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: hub.docker.com
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build Docker
        run: |
          echo 'Building docker image'
          docker build --no-cache --rm -t hub.docker.com/${{secrets.DOCKER_USERNAME}}/projeto-integrador_api:$DOCKERTAG .
          echo 'Pushing the docker image ...'
          echo 'Done (-:'

      - name: Trivy Scanning
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'hub.docker.com/${{secrets.DOCKER_USERNAME}}/projeto-integrador_api:$DOCKERTAG'
          format: 'table'
          output: 'trivy-results.txt'

      - name: Upload report Trivy
        uses: actions/upload-artifact@v2
        with:
          name: Trivy
          path: |
            trivy-results.txt

      
      - name: Push to docker 
        run: docker push hub.docker.com/${{secrets.DOCKER_USERNAME}}/projeto-integrador_api:$DOCKERTAG

      - name: End
        run: |
          echo "Thats all folks!"